### ISSUE TITLE
Uncaught Error: Line number (5) greater than maximum line (4)

### ISSUE THREAD

**Issue by fzzr-** [AtomLinter/linter-sass-lint#124]
[Enter steps to reproduce below:]
1. open/create new document `.xml`
2. save it with content:

``` xml
<?xml version="1.0"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
     width="60px" height="60px" viewBox="-0.5 -0.5 60 60" enable-background="new -0.5 -0.5 60 60" xml:space="preserve">
```

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [linter-sass-lint](https://github.com/AtomLinter/linter-sass-lint) package, v1.6.1
### Stack Trace

Uncaught Error: Line number (5) greater than maximum line (4)

```
At ~/.atom/packages/linter-sass-lint/node_modules/atom-linter/lib/index.js:165

Error: Line number (5) greater than maximum line (4)
    at Object.rangeFromLineNumber (~/.atom/packages/linter-sass-lint/node_modules/atom-linter/lib/index.js:165:11)
    at ~/.atom/packages/linter-jing/lib/validate.js:34:24
    at Array.map (native)
    at Socket.<anonymous> (~/.atom/packages/linter-jing/lib/validate.js:82:72)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```
### Commands

```
     -0:26.2.0 core:confirm (input.hidden-input)
     -0:24.6.0 pane:show-previous-item (input.hidden-input)
     -0:23 core:copy (input.hidden-input)
     -0:21.6.0 core:move-right (input.hidden-input)
  2x -0:20.7.0 core:select-up (input.hidden-input)
     -0:19.2.0 editor:select-to-first-character-of-line (input.hidden-input)
     -0:17.8.0 core:move-left (input.hidden-input)
  5x -0:17.1.0 core:select-down (input.hidden-input)
     -0:15.1.0 core:copy (input.hidden-input)
     -0:14.1.0 pane:show-next-item (input.hidden-input)
     -0:13.2.0 core:paste (input.hidden-input)
  4x -0:10.5.0 core:move-up (input.hidden-input)
     -0:09.0 editor:delete-line (input.hidden-input)
  4x -0:04.7.0 core:move-down (input.hidden-input)
     -0:02.8.0 bracket-matcher:close-tag (input.hidden-input)
     -0:02.2.0 window:save-all (input.hidden-input)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      ".haxe.source": [
        "dump"
      ],
      "text.xml": [
        "tei",
        "svg"
      ]
    },
    "destroyEmptyPanes": true,
    "disabledPackages": [
      "metrics",
      "aligner-python",
      "path-hyperclick",
      "linter-glsl",
      "linter-perl-check-syntax",
      "Haxelang",
      "autocomplete-glsl",
      "autocomplete-go",
      "autocomplete-java",
      "builder-go",
      "env-from-shell",
      "environment",
      "go-config",
      "flow",
      "go-get",
      "go-plus",
      "gofmt",
      "gometalinter-linter",
      "gorename",
      "language-actionscript3",
      "sublime-block-comment",
      "language-toml",
      "language-ruby-on-rails",
      "file-icons",
      "lime",
      "linter-javac",
      "navigator-godef",
      "tester-go"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".hgcheck",
      ".svn",
      ".DS_Store",
      "Thumbs.db",
      ".*.hx",
      "._*"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "todo",
      "aligner",
      "activate-power-mode",
      "perldoc",
      "block-comment-plus"
    ],
    "projectHome": "~/Developer/Projects/"
  },
  "linter-sass-lint": {}
}
```
### Installed Packages

``` coffee
# User
aligner, v0.22.0
aligner-css, v1.2.0
aligner-scss, v1.1.0
atom-hg, v2.0.4
autocomplete-paths, v1.0.2
autocomplete-python, v1.8.4
autocomplete-xml, v0.8.3
block-comment-plus, v0.4.0
haxe, v0.8.14
language-cmake, v0.2.0
language-ethereum, v0.3.9
language-glsl, v2.0.1
language-haxe, v0.4.4
language-ini, v1.16.0
language-svg, v0.9.0
language-vcard, v0.2.0
linter, v1.11.14
linter-coffeelint, v1.1.2
linter-jing, v0.4.3
linter-pep8, v1.3.0
linter-perl, v0.8.0
linter-sass-lint, v1.6.1
linter-scss-lint, v3.0.4
python-tools, v0.6.8

# Dev
No dev packages
```

**Comment by DanPurdy** [comment]
I can't recreate this in Atom 1.8 but funnily enough I had the same error earlier on with linter-eslint.

Does this consistently happen for you or was it just a one off?

**Comment by fzzr-** [comment]
It happens couple of times.

**Comment by DanPurdy** [comment]
Still haven't recreated in the months ive been using this linter.
