### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by macgyver** [AtomLinter/linter-sass-lint#172]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [linter-sass-lint](https://github.com/AtomLinter/linter-sass-lint) package 1.7.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, uv_chdir

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/graceful-fs/polyfills.js:21

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at process.chdir (/Applications/Atom.app/Contents/Resources/app/node_modules/graceful-fs/polyfills.js:21:9)
    at process.chdir (/Applications/Atom.app/Contents/Resources/app/node_modules/graceful-fs/polyfills.js:21:9)
    at process.chdir (/packages/linter-sass-lint/node_modules/graceful-fs/polyfills.js:18:9)
    at lint (/packages/jshint/index.js:229:10)
    at complete (/packages/jshint/node_modules/lodash/index.js:7697:25)
    at delayed (/packages/jshint/node_modules/lodash/index.js:7707:11)
```

### Commands

```
  7x -0:12.9.0 blur (input.hidden-input)
     -0:12.7.0 pane:show-previous-item (input.hidden-input)
  7x -0:12.7.0 blur (input.hidden-input)
     -0:12.3.0 pane:show-previous-item (input.hidden-input)
  7x -0:12.3.0 blur (input.hidden-input)
     -0:11.6.0 pane:show-previous-item (input.hidden-input)
  7x -0:11.6.0 blur (input.hidden-input)
     -0:09.9.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
  3x -0:09.9.0 blur (input.hidden-input)
     -0:05.9.0 core:move-down (input.hidden-input)
     -0:05.6.0 core:confirm (input.hidden-input)
  9x -0:05.6.0 blur (input.hidden-input)
     -0:05.1.0 ex-mode:open (input.hidden-input)
  3x -0:05.1.0 blur (input.hidden-input)
     -0:04.4.0 core:confirm (input.hidden-input)
  5x -0:04.4.0 blur (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
an-old-hope-syntax 1.0.4 
atom-monokai 0.10.9 
atom-ternjs 0.18.3 
AtomicFreckle 0.2.0 
busy-signal 1.4.1 
coffee-compile 0.25.0 
color-picker 2.2.5 
dracula-theme 2.0.3 
dracula-ui 0.4.1 
dudeness-syntax 0.1.0 
duotone-dark-earth-syntax 2.1.0 
duotone-dark-forest-syntax 2.1.0 
duotone-dark-sea-syntax 2.1.0 
duotone-dark-space-syntax 2.1.0 
duotone-dark-syntax 2.1.0 
editorconfig 2.2.2 
ex-mode 0.14.0 
file-icons 2.1.5 
filter-syntax 0.3.0 
fizzy 0.21.0 
highlight-selected 0.13.1 
hyperclick 0.0.40 
intentions 1.1.2 
js-hyperclick 1.11.0 
jsformat 0.9.3 
jshint 1.8.6 
language-babel 2.61.0 
language-javascript-jsx 0.3.7 
last-tab 0.1.6 
linter 2.1.4 
linter-coffeescript 1.0.0 
linter-csslint 1.3.4 
linter-eslint 8.1.7 
linter-flake8 2.2.1 
linter-sass-lint 1.7.4 
linter-scss-lint 3.1.0 
linter-stylelint undefined 
linter-ui-default 1.5.0 
merge-conflicts 1.4.5 
minimap 4.28.2 
multi-cursor 2.1.5 
node-debugger 1.10.1 
octocat-syntax 1.3.1 
pigments 0.39.1 
pretty-json 1.6.3 
python-tools 0.6.9 
react 0.16.2 
spectrum-light-syntax 0.0.5 
stylefmt 4.1.1 
tablr 1.8.3 
uglify 1.3.1 
vim-mode 0.66.0 
```

**Comment by Arcanemagus** [comment]
> `at lint (/packages/jshint/index.js:229:10)`

This is actually caused by the deprecated [jshint](https://atom.io/packages/jshint) package. You should uninstall that and either install [linter-jshint](https://atom.io/packages/linter-jshint) or preferably for your sake move to a modern linter like ESLint ([linter-eslint](https://atom.io/packages/linter-eslint)).
